#include "Classes.h"

std::vector<TESClass> classicClasses = {
    {"$Acrobat",
     {"speech", "oneHanded", "block", "archery", "lockpicking", "pickpocket", "sneak"},
     "$Stealth",
     "$Acrobat_Description"},
    {"$Agent",
     {"block", "illusion", "archery", "speech", "lockpicking", "pickpocket", "sneak"},
     "$Stealth",
     "$Agent_Description"},
    {"$Archer",
     {"smithing", "oneHanded", "twoHanded", "block", "lightArmor", "archery", "sneak"},
     "$Combat",
     "$Archer_Description"},
    {"$Assassin",
     {"sneak", "alchemy", "oneHanded", "lightArmor", "archery", "pickpocket", "lockpicking"},
     "$Stealth",
     "$Assassin_Description"},
    {"$Barbarian",
     {"smithing", "archery", "oneHanded", "block", "twoHanded", "lightArmor", "destruction"},
     "$Combat",
     "$Barbarian_Description"},
    {"$Bard",
     {"alchemy", "oneHanded", "block", "illusion", "lightArmor", "speech", "twoHanded"},
     "$Stealth",
     "$Bard_Description"},
    {"$Battlemage",
     {"alchemy", "alteration", "oneHanded", "twoHanded", "conjuration", "destruction", "illusion"},
     "$Magic",
     "$Battlemage_Description"},
    {"$Crusader",
     {"speech", "oneHanded", "twoHanded", "destruction", "lightArmor", "heavyArmor", "restoration"},
     "$Combat",
     "$Crusader_Description"},
    {"$Healer",
     {"alchemy", "alteration", "destruction", "illusion", "speech", "restoration", "block"},
     "$Magic",
     "$Healer_Description"},
    {"$Knight",
     {"oneHanded", "twoHanded", "block", "heavyArmor", "illusion", "speech", "enchanting"},
     "$Combat",
     "$Knight_Description"},
    {"$Mage",
     {"alchemy", "alteration", "conjuration", "destruction", "illusion", "restoration", "speech"},
     "$Magic",
     "$Mage_Description"},
    {"$Monk",
     {"sneak", "alteration", "oneHanded", "speech", "archery", "lockpicking", "restoration"},
     "$Stealth",
     "$Monk_Description"},
    {"$Nightblade",
     {"alchemy", "alteration", "enchanting", "oneHanded", "destruction", "lightArmor", "restoration"},
     "$Magic",
     "$Nightblade_Description"},
    {"$Pilgrim",
     {"smithing", "block", "oneHanded", "lightArmor", "speech", "lockpicking", "twoHanded"},
     "$Stealth",
     "$Pilgrim_Description"},
    {"$Rogue",
     {"alchemy", "sneak", "oneHanded", "block", "illusion", "lightArmor", "speech"},
     "$Combat",
     "$Rogue_Description"},
    {"$Scout",
     {"sneak", "alchemy", "smithing", "lockpicking", "oneHanded", "block", "lightArmor"},
     "$Combat",
     "$Scout_Description"},
    {"$Sorcerer",
     {"alchemy", "alteration", "conjuration", "destruction", "heavyArmor", "illusion", "restoration"},
     "$Magic",
     "$Sorcerer_Description"},
    {"$Spellsword",
     {"alteration", "oneHanded", "block", "heavyArmor", "destruction", "illusion", "restoration"},
     "$Magic",
     "$Spellsword_Description"},
    {"$Thief",
     {"sneak", "lightArmor", "archery", "speech", "pickpocket", "lockpicking", "oneHanded"},
     "$Stealth",
     "$Thief_Description"},
    {"$Warrior",
     {"smithing", "twoHanded", "oneHanded", "block", "heavyArmor", "archery", "lightArmor"},
     "$Combat",
     "$Warrior_Description"},
    {"$Witchhunter",
     {"alchemy", "sneak", "conjuration", "destruction", "archery", "illusion", "lockpicking"},
     "$Magic",
     "$Witchhunter_Description"},
};

std::vector<TESClass> classicClassesConstellations = {
    {"$Acrobat",
     {"speech", "athletics", "block", "archery", "lockpicking", "pickpocket", "sneak"},
     "$Stealth",
     "$Acrobat_Description"},
    {"$Agent",
     {"athletics", "illusion", "archery", "speech", "lockpicking", "pickpocket", "sneak"},
     "$Stealth",
     "$Agent_Description"},
    {"$Archer",
     {"smithing", "oneHanded", "twoHanded", "handToHand", "lightArmor", "archery", "sneak"},
     "$Combat",
     "$Archer_Description"},
    {"$Assassin",
     {"sneak", "alchemy", "oneHanded", "lightArmor", "archery", "athletics", "lockpicking"},
     "$Stealth",
     "$Assassin_Description"},
    {"$Barbarian",
     {"smithing", "athletics", "oneHanded", "block", "twoHanded", "lightArmor", "handToHand"},
     "$Combat",
     "$Barbarian_Description"},
    {"$Bard",
     {"alchemy", "oneHanded", "block", "illusion", "lightArmor", "speech", "athletics"},
     "$Stealth",
     "$Bard_Description"},
    {"$Battlemage",
     {"alchemy", "alteration", "oneHanded", "twoHanded", "conjuration", "destruction", "illusion"},
     "$Magic",
     "$Battlemage_Description"},
    {"$Crusader",
     {"athletics", "oneHanded", "twoHanded", "destruction", "handToHand", "heavyArmor", "restoration"},
     "$Combat",
     "$Crusader_Description"},
    {"$Healer",
     {"alchemy", "alteration", "destruction", "illusion", "speech", "restoration", "sorcery"},
     "$Magic",
     "$Healer_Description"},
    {"$Knight",
     {"oneHanded", "twoHanded", "block", "heavyArmor", "illusion", "speech", "handToHand"},
     "$Combat",
     "$Knight_Description"},
    {"$Mage",
     {"alchemy", "alteration", "conjuration", "destruction", "illusion", "restoration", "sorcery"},
     "$Magic",
     "$Mage_Description"},
    {"$Monk",
     {"sneak", "alteration", "athletics", "handToHand", "archery", "lockpicking", "restoration"},
     "$Stealth",
     "$Monk_Description"},
    {"$Nightblade",
     {"athletics", "alteration", "sneak", "oneHanded", "destruction", "lightArmor", "restoration"},
     "$Magic",
     "$Nightblade_Description"},
    {"$Pilgrim",
     {"smithing", "block", "oneHanded", "lightArmor", "speech", "lockpicking", "twoHanded"},
     "$Stealth",
     "$Pilgrim_Description"},
    {"$Rogue",
     {"alchemy", "athletics", "oneHanded", "block", "illusion", "lightArmor", "speech"},
     "$Combat",
     "$Rogue_Description"},
    {"$Scout",
     {"athletics", "alchemy", "smithing", "lockpicking", "oneHanded", "block", "lightArmor"},
     "$Combat",
     "$Scout_Description"},
    {"$Sorcerer",
     {"alchemy", "alteration", "conjuration", "destruction", "heavyArmor", "sorcery", "restoration"},
     "$Magic",
     "$Sorcerer_Description"},
    {"$Spellsword",
     {"alteration", "oneHanded", "block", "heavyArmor", "destruction", "illusion", "restoration"},
     "$Magic",
     "$Spellsword_Description"},
    {"$Thief",
     {"sneak", "lightArmor", "archery", "speech", "pickpocket", "lockpicking", "athletics"},
     "$Stealth",
     "$Thief_Description"},
    {"$Warrior",
     {"smithing", "twoHanded", "oneHanded", "block", "heavyArmor", "handToHand", "athletics"},
     "$Combat",
     "$Warrior_Description"},
    {"$Witchhunter",
     {"alchemy", "athletics", "conjuration", "destruction", "archery", "illusion", "lockpicking"},
     "$Magic",
     "$Witchhunter_Description"},
};

std::vector<TESClass> classicClassesFirmament = {
    {"$Acrobat",
     {"speech", "athletics", "block", "archery", "lockpicking", "pickpocket", "sneak"},
     "$Stealth",
     "$Acrobat_Description"},
    {"$Agent",
     {"athletics", "illusion", "archery", "speech", "lockpicking", "pickpocket", "sneak"},
     "$Stealth",
     "$Agent_Description"},
    {"$Archer",
     {"smithing", "oneHanded", "horseman", "handToHand", "lightArmor", "archery", "sneak"},
     "$Combat",
     "$Archer_Description"},
    {"$Assassin",
     {"sneak", "alchemy", "oneHanded", "lightArmor", "archery", "athletics", "lockpicking"},
     "$Stealth",
     "$Assassin_Description"},
    {"$Barbarian",
     {"smithing", "athletics", "oneHanded", "block", "twoHanded", "lightArmor", "handToHand"},
     "$Combat",
     "$Barbarian_Description"},
    {"$Bard",
     {"philosophy", "oneHanded", "block", "illusion", "lightArmor", "speech", "athletics"},
     "$Stealth",
     "$Bard_Description"},
    {"$Battlemage",
     {"alchemy", "alteration", "oneHanded", "twoHanded", "conjuration", "destruction", "illusion"},
     "$Magic",
     "$Battlemage_Description"},
    {"$Crusader",
     {"athletics", "oneHanded", "twoHanded", "destruction", "handToHand", "heavyArmor", "restoration"},
     "$Combat",
     "$Crusader_Description"},
    {"$Healer",
     {"alchemy", "alteration", "destruction", "illusion", "speech", "restoration", "sorcery"},
     "$Magic",
     "$Healer_Description"},
    {"$Knight",
     {"oneHanded", "twoHanded", "block", "heavyArmor", "horseman", "speech", "handToHand"},
     "$Combat",
     "$Knight_Description"},
    {"$Mage",
     {"alchemy", "alteration", "conjuration", "destruction", "illusion", "restoration", "sorcery"},
     "$Magic",
     "$Mage_Description"},
    {"$Monk",
     {"sneak", "alteration", "athletics", "handToHand", "archery", "lockpicking", "restoration"},
     "$Stealth",
     "$Monk_Description"},
    {"$Nightblade",
     {"athletics", "alteration", "sneak", "oneHanded", "destruction", "lightArmor", "restoration"},
     "$Magic",
     "$Nightblade_Description"},
    {"$Pilgrim",
     {"smithing", "block", "oneHanded", "lightArmor", "speech", "philosophy", "exploration"},
     "$Stealth",
     "$Pilgrim_Description"},
    {"$Rogue",
     {"alchemy", "athletics", "oneHanded", "block", "illusion", "lightArmor", "speech"},
     "$Combat",
     "$Rogue_Description"},
    {"$Scout",
     {"athletics", "alchemy", "smithing", "exploration", "oneHanded", "block", "lightArmor"},
     "$Combat",
     "$Scout_Description"},
    {"$Sorcerer",
     {"alchemy", "alteration", "conjuration", "destruction", "heavyArmor", "sorcery", "restoration"},
     "$Magic",
     "$Sorcerer_Description"},
    {"$Spellsword",
     {"alteration", "oneHanded", "block", "heavyArmor", "destruction", "illusion", "restoration"},
     "$Magic",
     "$Spellsword_Description"},
    {"$Thief",
     {"sneak", "lightArmor", "archery", "speech", "pickpocket", "lockpicking", "athletics"},
     "$Stealth",
     "$Thief_Description"},
    {"$Warrior",
     {"smithing", "twoHanded", "oneHanded", "block", "heavyArmor", "handToHand", "athletics"},
     "$Combat",
     "$Warrior_Description"},
    {"$Witchhunter",
     {"alchemy", "athletics", "conjuration", "destruction", "archery", "illusion", "exploration"},
     "$Magic",
     "$Witchhunter_Description"},
};
